### ISSUE TITLE
'Not found - Request ID' error after signing in

### ISSUE THREAD

**Issue by samwzlim** [cprecioso/Fling-Spotify.shortcut#1]
![image](https://user-images.githubusercontent.com/74489037/134621663-90cf5b37-ed93-4220-8883-cadeadfaadfb.png)

Hi! I am facing this error after signing in to my spotify account, why is that? I have a Spotify Premium account. I have already tried on multiple devices and get the same error. Please help!

**Comment by cprecioso** [comment]
Hi, I'm on vacation right now. It seems like a service I had created to adapt the shortcut to Spotify API has been removed from its host. You won't be able to make it work for now. As soon as I'm back next week, I'll look into getting it back up.

**Comment by cprecioso** [comment]
It seems I did add the code for the online service in here, if you have the knowledge to host the `oauth-proxy` folder somewhere you can point the shortcut there and get it working.

**Comment by samwzlim** [comment]
> It seems I did add the code for the online service in here, if you have the knowledge to host the `oauth-proxy` folder somewhere you can point the shortcut there and get it working.

I don't think I have the abilities to do that, I'll just wait for you to be back next week to set it up. Enjoy your vacation :)

**Comment by cprecioso** [comment]
Hi @samwzlim, I deployed the code again now, can you check if it works?

**Comment by samwzlim** [comment]
> Hi @samwzlim, I deployed the code again now, can you check if it works?

Hi, it's working now and it's so seamless! Thanks for your work!

I have a question. Is it possible to switch playback to a spotify connect device automatically after running the shortcut? At the moment, upon running the shortcut, there is a prompt which requires me to select which device I want to switch to:
![image](https://user-images.githubusercontent.com/74489037/134829743-e3b27a7e-e9c5-46f1-8869-607a48f719c8.png)

**Comment by cprecioso** [comment]
You can edit the shortcut yourself in order to do that.

1. Put a "copy to pasteboard" action right before the "fling to device" comment. It should copy the `SelectedDevice` variable.
2. Run the workflow and select the device you'd like to always fling to. At the end of the workflow, it's ID will be copied into your pasteboard.
3. Delete all the actions in the "enumerate devices" and "choose device" sections. You can replace them for just one action that sets the value of the `SelectedDevice` variable to the value you just got in the pasteboard in the previous step.
4. Done

Try it out, tell me if you have any problems.
I'm going to close the issue as the problem has been solved, but feel free to continue this topic here if you need further help.

**Comment by samwzlim** [comment]
> You can edit the shortcut yourself in order to do that.
> 
>     1. Put a "copy to pasteboard" action right before the "fling to device" comment. It should copy the `SelectedDevice` variable.
> 
>     2. Run the workflow and select the device you'd like to always fling to. At the end of the workflow, it's ID will be copied into your pasteboard.
> 
>     3. Delete all the actions in the "enumerate devices" and "choose device" sections. You can replace them for just one action that sets the value of the `SelectedDevice` variable to the value you just got in the pasteboard in the previous step.
> 
>     4. Done
> 
> 
> Try it out, tell me if you have any problems.
> I'm going to close the issue as the problem has been solved, but feel free to continue this topic here if you need further help.

It did the trick, thank you very much! However, I noticed that the shortcut does not detect Google Cast devices, but rather, only detects Spotify Connect devices. I have a raspberry pi connected to my hifi running SpoCon, a spotify connect client which runs 24/7, and Fling Spotify is able to see this device all the time. However, my google cast devices such as the nest mini and nest hub are not detected by Fling Spotify unless I manually select the google cast device from the spotify app on my iPhone, then only it shows up on Fling Spotify. If I change playback to another device, the google cast device disappears again from Fling Spotify. Is this a limitation with Spotify's API?

Please refer to the images below, `Samuel's Study Room Speaker` is my raspberry pi running the spotify connect client, 'Samuel's Bedroom Speaker` is my Google Cast device. In each image, I chose the specified device in Spotify before running the shortcut.
![image](https://user-images.githubusercontent.com/74489037/134845207-2034e267-b0b8-4fc7-bb01-adb6aa4cedc7.png)
![image](https://user-images.githubusercontent.com/74489037/134845348-5592b883-f989-4dec-8f5d-e616d8fe47e6.png)
![image](https://user-images.githubusercontent.com/74489037/134845219-647326e3-82f7-47c8-b8e5-1a50efe2a04e.png)

**Comment by cprecioso** [comment]
I can't do anything about that, Google Cast devices are detected from the Spotify _app_, which I can't communicate with; I can only talk with the Spotify _server_, which can't find Google Cast.

**Comment by samwzlim** [comment]
> I can't do anything about that, Google Cast devices are detected from the Spotify _app_, which I can't communicate with; I can only talk with the Spotify _server_, which can't find Google Cast.

Oh I see, it's alright then :)
